select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--No. of customers that satisfy Q2.
select
count(*) filter (where discount_applied = 'Yes'
and purchase_amount >= (select avg(purchase_amount) from customer)) as qualifying_customers,
count(*) as total_customers
from customer

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric), 2) as "Avg Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the avg purchase amount in the standard and express shipping.
select shipping_type, round(avg(purchase_amount), 2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare avg spend and total revenue
--between subscribers and non-subscribers.
select subscription_status, 
count(customer_id) as "Total Customers", 
sum(purchase_amount) as "Total Revenue", 
round(avg(purchase_amount), 2) as "Average Spend"
from customer
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with the discounts applied?
--this query finds the products with most discount applied out of total product purchases.
--(answer to our question)
select item_purchased,
round(100 * sum(case when discount_applied ='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--this query finds the products with most discount applied out of total discount applied products.
--(not the answer to our question)
select item_purchased, count(item_purchased)
from customer
where discount_applied = 'Yes'
group by item_purchased
order by count(item_purchased) desc
limit 5;

--Q7. Segment customers into New, Returning and Loyal based on their total
--number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer
)

select customer_segment, count(*) as "No of Customers"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?
--(for one category)
select item_purchased, count(item_purchased)
from customer
where category = 'Clothing'
group by item_purchased
order by count(item_purchased) desc
limit 3;

--(for all categories)
with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also more likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Find the prob. that a given customer is a subscriber given that they are a repeat buyer (bayes theorem)
with probabilities as (
select
count(*) filter (
where subscription_status = 'Yes')::numeric/count(*) as p_s,
count(*) filter (
where previous_purchases > 5)::numeric/count(*) as p_r,
count(*) filter (
where subscription_status = 'Yes' and previous_purchases > 5)::numeric/count(*) as p_r_given_s
from customer
)
select
round(p_r_given_s,3) as "P(Repeat Buyer | Subscriber)", round(p_s,3) as "P(Subscriber)", 
round(p_r,3) as "P(Repeat Buyer)",
round((p_r_given_s * p_s/p_r),3) as "P(Subscriber | Repeat Buyer)"
from probabilities;

--Q10. What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_rev
from customer
group by age_group
order by total_rev desc 